added the (not working) dynarec and lightning (needed by the dynarec)
git-svn-id: https://yabause.svn.sourceforge.net/svnroot/yabause/trunk@387 d7be59e3-070e-4b9a-85a1-4646befae34d

diff --git a/yabause/configure b/yabause/configure
--- a/yabause/configure
+++ b/yabause/configure
@@ -271,7 +271,7 @@ PACKAGE_VERSION='0.5'
 PACKAGE_STRING='yabause 0.5'
 PACKAGE_BUGREPORT=''
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os yabause_arch INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE HAVE_LIBSDL ac_ct_HAVE_LIBSDL HAVE_PKG ac_ct_HAVE_PKG yabause_yui LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os yabause_arch INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE HAVE_LIBSDL ac_ct_HAVE_LIBSDL HAVE_PKG ac_ct_HAVE_PKG yabause_yui DYNAREC_TRUE DYNAREC_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4343,11 +4343,32 @@ fi;
 # Check whether --enable-dynarec or --disable-dynarec was given.
 if test "${enable_dynarec+set}" = set; then
   enableval="$enable_dynarec"
+  case "${enableval}" in
+       yes) dynarec=true ;;
+       no)  dynarec=false ;;
+       *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-dynarec" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-dynarec" >&2;}
+   { (exit 1); exit 1; }; } ;;
+     esac
+else
+  dynarec=false
+fi;
+
+
+if test x$dynarec = xtrue; then
+  DYNAREC_TRUE=
+  DYNAREC_FALSE='#'
+else
+  DYNAREC_TRUE='#'
+  DYNAREC_FALSE=
+fi
+
+if test x$dynarec = xtrue ; then
   cat >>confdefs.h <<\_ACEOF
 #define DYNAREC 1
 _ACEOF
 
-fi;
+fi
 
                               ac_config_files="$ac_config_files Makefile src/Makefile doc/Makefile"
 
@@ -4477,6 +4498,13 @@ if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"AMDEP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${DYNAREC_TRUE}" && test -z "${DYNAREC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"DYNAREC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"DYNAREC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5060,6 +5088,8 @@ s,@ac_ct_HAVE_LIBSDL@,$ac_ct_HAVE_LIBSDL,;t t
 s,@HAVE_PKG@,$HAVE_PKG,;t t
 s,@ac_ct_HAVE_PKG@,$ac_ct_HAVE_PKG,;t t
 s,@yabause_yui@,$yabause_yui,;t t
+s,@DYNAREC_TRUE@,$DYNAREC_TRUE,;t t
+s,@DYNAREC_FALSE@,$DYNAREC_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
